### ISSUE TITLE
Cannot download the embeddings.zip

### ISSUE THREAD

**Issue by yanniangu** [cmavro/GRAD#1]
Thank you so much for all your work, it has been very inspiring. But when I want to reproduce the code, it is difficult to download the pre-trained GradBERT node embeddings from google drive, could you please upload the file to Baidu Cloud so that Chinese users can download it, thank you very much!

**Comment by cmavro** [comment]
Hi, 

Thank you for your interest in our work. Can you access/download them from here [https://archive.org/download/gradbert_embeddings](https://archive.org/download/gradbert_embeddings) ?

**Comment by yanniangu** [comment]
Thx a lot for helping me!
